[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-lc++",
  "-C", "link-arg=-lc++abi",
  "-C", "link-arg=-static",
  "-C", "target-feature=+crt-static",
  "-L", "/usr/lib/x86_64-linux-musl",
]

[env]
CC_x86_64-unknown-linux-musl = "clang"
CXX_x86_64-unknown-linux-musl = "clang++"
AR_x86_64-unknown-linux-musl = "ar"
CFLAGS_x86_64-unknown-linux-musl = "-fPIC"
CXXFLAGS_x86_64-unknown-linux-musl = "-fPIC -stdlib=libc++"
